version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    networks:
      - Saul_Goodman_1
    volumes:
      - Huell_Babi_1:/var/www/html/
    depends_on:
      - wordpress
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    env_file:
      - ./.env
    networks:
      - Saul_Goodman_1
    volumes:
      - Huell_Babi_1:/var/www/html/
    depends_on:
      - mariadb
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file:
      - ./.env
    networks:
      - Saul_Goodman_1
    volumes:
      - Huell_Babi_2:/var/lib/
    restart: always
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    env_file:
      - ./.env
    networks:
      - Saul_Goodman_1
    volumes:
      - Huell_Babi_1:/var/www/html/
    depends_on:
      - wordpress
    restart: always
  vsftpd:
    container_name: vsftpd
    build:
      context: ./requirements/bonus/vsftpd
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASS: ${FTP_PASS}
    env_file:
      - ./.env
    networks:
      - Saul_Goodman_1
    ports:
      - 21:21
      - 4242-4262:4242-4262
    volumes:
      - Huell_Babi_1:/var/www/html/
    depends_on:
      - wordpress
    restart: always
  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
    env_file:
      - ./.env
    networks:
      - Saul_Goodman_1
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    restart: always
  static_site:
    container_name: static_site
    build:
      context: ./requirements/bonus/static_site
    ports:
      - 80:80
    networks:
      - Saul_Goodman_1
    restart: always
  portainer:
    container_name: portainer
    build:
      context: ./requirements/bonus/portainer
    env_file:
      - ./.env
    networks:
      - Saul_Goodman_1
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  Saul_Goodman_1:
    driver: bridge

volumes:
  Huell_Babi_1:
    driver_opts:
      type: "none"
      o: "bind"
      device: /home/${USER}/data/wordpress

  Huell_Babi_2:
    driver_opts:
      type: "none"
      o: "bind"
      device: /home/${USER}/data/database
