version: '3'

services:
  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - 80:80
      - 443:443
    networks:
     - Saul_Goodman_1
    volumes:
     - Huell_Babi_1:/var/www/html/
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    build: ./wordpress/
    #command: ["/usr/sbin/php-fpm7.3", "--nodaemonize"]
    env_file:
      - ./.env
    networks:
      - Saul_Goodman_1
      - Saul_Goodman_2
    volumes:
      - Huell_Babi_1:/var/www/html/
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb
    build: ./mariadb/
    env_file:
      - ./.env
    networks:
      - Saul_Goodman_2
    volumes:
      - Huell_Babi_2:/var/lib/
  redis:
    container_name: redis
    build: ./bonus/redis
    #command: ["/usr/sbin/php-fpm7.3", "--nodaemonize"]
    env_file:
      - ./.env
    networks:
      - Saul_Goodman_1
      - Saul_Goodman_2
    volumes:
      - Huell_Babi_1:/var/www/html/
    depends_on:
      - wordpress
  vsftpd:
    container_name: vsftpd
    build:
      context: ./bonus/vsftpd
      args:
        FTP_USER: ${FTP_USER}
        FTP_PASS: ${FTP_PASS}
    env_file:
      - ./.env
    networks:
      - Saul_Goodman_1
      - Saul_Goodman_2
    ports:
      - 21:21
      - 4242-4262:4242-4262
    volumes:
      - Huell_Babi_1:/var/www/html/
    depends_on:
      - wordpress
  adminer:
    container_name: adminer
    build:
      context: ./bonus/adminer
      # args:
      #   FTP_USER: ${FTP_USER}
      #   FTP_PASS: ${FTP_PASS}
    env_file:
      - ./.env
    networks:
      - Saul_Goodman_1
      - Saul_Goodman_2
    ports:
      - 8080:8080
    depends_on:
      - mariadb

networks:
 Saul_Goodman_1:
   driver: bridge
 Saul_Goodman_2:
   driver: bridge

networks:
 Saul_Goodman_1:
   driver: bridge
 Saul_Goodman_2:
   driver: bridge

volumes:
  Huell_Babi_1:
    driver_opts:
      type: "none"
      o: "bind"
      device: "/opt/data/wp-data"

  Huell_Babi_2:
    driver_opts:
      type: "none"
      o: "bind"
      device: "/opt/data/database"
